<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Purchases.Application\Purchases.Application.csproj" />
    <ProjectReference Include="..\Purchases.Infrastructure\Purchases.Infrastructure.csproj" />
    <ProjectReference Include="..\SharedPresentation\SharedPresentation.csproj" />
  </ItemGroup>

</Project>
